### ISSUE TITLE
[Feature Request] Add Ut Video/H.264 RGB codec, PCM 16-bit signed little endian/FLAC audio codec and AVI container

### ISSUE THREAD

**Issue by fsvgm777** [psyGamer/TASRecorder#6]
Since TASRecorder uses FFmpeg as a base, it shouldn't be too difficult to add these in the options. Note that Ut Video is a lossless video codec, and PCM 16-bit signed little endian is uncompressed audio.

This would allow lossless recording of Celeste TASes in Everest.

**Comment by psyGamer** [comment]
That seems doable. You can already set the output codec to whatevery you want by setting the `Video/AudioCodecOverwrite` in the `modsettings-TASRecorder.celeste`. The values are the `AVCodecID`s from FFmpeg.
But if it works, i can add it as a preset.

**Comment by psyGamer** [comment]
Both Ut Video and PCM seem to be incompatable with most containers...
What do you think about supporting H.264 `-crf 0` and FLAC?

**Comment by fsvgm777** [comment]
That should work, although I would prefer H.264 RGB `-qp 0` (it's a separate entry entirely), so that it produces lossless H.264 RGB.

And yeah, that's why I suggested adding an option to add the AVI container, since that works best with Ut Video and PCM.

**Comment by psyGamer** [comment]
Oh, I didn't see the AVI since it was in the title...
I could take a look at that.

**Comment by psyGamer** [comment]
I can't really get AVI to work with libavcodec/libavforamt.
Using the `ffmpeg` CLI works, which is strange...
I think limiting it to H.264 RGB might be enough

**Comment by fsvgm777** [comment]
Following up from (this comment)[[this comment](https://github.com/psyGamer/TASRecorder/issues/5#issuecomment-1763164181)] (which has a test build that includes H.264 RGB and FLAC, the video output is actually YUV420P instead of RGB. Shouldn't be too hard to fix, though.

**Comment by fsvgm777** [comment]
Sounds good enough for me.

**Comment by psyGamer** [comment]
Could you try this build and see if it fits your needs?
[TASRecorder.zip](https://github.com/psyGamer/TASRecorder/files/13033674/TASRecorder.zip)

**Comment by fsvgm777** [comment]
Apologies for the late response, but from quick testing, it should fit my needs decently well (only thing missing is dumping to AVI, but not a dealbreaker).

**Comment by psyGamer** [comment]
You can try changing the file extension for automatic detection and set overwrites for audio and video codec (`AV_CODEC_ID`) in `modsettings-TASRecorder.celeste`
If that works for you, great! But I dont like to include presets which i cant test myself.

**Comment by psyGamer** [comment]
Fixed in 68ed91da27adcb80094df47d9d013cb770a79838 and 94c08f7b5fd275789b48a066f7f8d2dd22052ac5
